O:
- =>O
BDE:
- 150xPE=>1xBDE
BSE:
- 1xAL 2xLST=>1xBSE
BTA:
- 1xFE 50xPE=>1xBTA
BBH:
- 2xAL 1xLST=>1xBBH
DW:
- 10xH2O 1xPG=>10xDW
PPA:
- 2xALG 1xH2O=>4xPPA
RAT:
- 1xGRN 1xALG 1xVEG=>10xRAT
BEA:
- 6xH2O=>4xBEA
GRN:
- 4xH2O=>4xGRN
RCO:
- 10xH2O 4xNS=>2xRCO
HCP:
- 14xH2O 1xNS=>8xHCP
VEG:
- 16xH2O 1xNS=>6xVEG
MAI:
- 20xH2O 2xNS=>12xMAI
DRF:
- 6xAL 1xHE=>1xDRF
OVE:
- 1xRCO 50xPE=>20xOVE
EXO:
- 10xOVE 1xAL 1xMFK=>10xEXO
PT:
- 1xSTL 1xTRN=>7xPT
C:
- 4xHCP=>4xC
BLE:
- 1xNA 1xCL 1xO=>3xBLE
SI:
- 3xSIO 1xC 1xO=>1xSI
AL:
- 6xALO 1xO 1xC 1xFLX=>4xAL
FE:
- 6xFEO 1xC 1xO 1xFLX=>4xFE
MUS:
- 4xNS=>12xMUS
PIB:
- 20xH2O 1xDDT 2xSOI=>12xPIB
GRA:
- 30xH2O 1xDDT 3xSOI=>6xGRA
HOP:
- 40xH2O 2xDDT 4xSOI=>18xHOP
SF:
- 1xAMM 2xGAL 3xH=>100xSF
HE3:
- =>HE3
RG:
- 10xGL 15xPG 1xSEN=>10xRG
GL:
- 2xSIO 1xNA 1xFLX=>12xGL
SIO:
- =>SIO
